# Site settings
title: Imkerverein Leondinger Bienen
email: matthias.baeck@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Der Imkerverein Leondinger Bienen setzt sich für die Förderung der Bienenzucht sowie die Unterstützung und die organisatorische Zusammenfassung seiner Mitglieder ein.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.leondinger-bienen.at" # the base hostname & protocol for your site
github_username:  leondinger-bienen

# Build settings
markdown: kramdown

exclude: ["bin", "bower_components", "jekyll", "node_modules", "obj", "styles/sass/*.*", "typings", "*.json", "app.*", "Gulpfile.js"]
